from llm import generate_sql
from db import execute_sql

def clean_sql_output(raw_sql):
    """
    Cleans markdown formatting from SQL generated by LLM.
    Removes triple backticks and 'sql' language tag.
    """
    cleaned = raw_sql.strip()
    if cleaned.startswith("```sql"):
        cleaned = cleaned[len("```sql"):].strip()
    if cleaned.endswith("```"):
        cleaned = cleaned[:-3].strip()
    return cleaned

def main():
    print("\U0001F916 AI DBA Agent is running. Type 'exit' to quit.\n")
    
    while True:
        user_input = input("\U0001F9E0 Enter your database task in plain English:\n> ").strip()
        
        if not user_input:
            print("⚠️  Please enter a valid instruction.")
            continue

        if user_input.lower() in ["exit", "quit"]:
            print("👋 Exiting AI DBA Agent. Goodbye!")
            break

        try:
            sql = generate_sql(user_input)
            cleaned_sql = clean_sql_output(sql)

            print("📝 Generated SQL:\n", cleaned_sql)
            result = execute_sql(cleaned_sql)
            print("📈 Execution Result:\n", result)

        except Exception as e:
            print("❌ Error:", e)

if __name__ == "__main__":
    main()
